apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: k8soperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Crud is the Schema for the cruds API
      displayName: Crud
      kind: Crud
      name: cruds.schedule.rs
      version: v1
  description: A sample k8s operator to deploy curd app
  displayName: k8soperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - k8soperator
  - curd
  links:
  - name: K8soperator
    url: https://k8soperator.domain
  maintainers:
  - email: rishi
    name: name1
  maturity: alpha
  provider:
    name: k8soperator-operator
  version: 0.0.0
