apiVersion: schedule.rs/v1
kind: Crud
metadata:
  labels:
    app.kubernetes.io/name: crud
    app.kubernetes.io/instance: crud-sample
    app.kubernetes.io/part-of: k8soperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8soperator
  name: crud-sample
spec:
  app:
    image: "testimage"
    name: "testapp"
    port: "78060"
    env:
      DBPATH: "testpath"
    svc:
      name: "appsvc"
      port: "78060"
      targetPort: "88080"
  db:
    image: "testimage"
    name: "testapp"
    port: "78060"
    env:
      DBPATH: "testpath"
    svc:
      name: "appsvc"
      port: "78060"
      targetPort: "88080"
  volume:
    capacity: "5gi"
    path: "/test/path"
    storage: "1Gi"
